name: CI

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: oven-sh/setup-bun@v1

      - name: Install
        run: bun install

      - name: Build
        run: bun run build

      - name: Check
        run: bun run check

      - name: Lint check
        run: bun lint:check

      - name: Prettier check
        run: bun prettier:check
