name: CI

on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        name: Install
        with:
          version: 8
          run_install: true

      - name: Build
        env:
          WERWAPP_SECRET: PLACEHOLDER
        run: pnpm run build

      - name: Check
        run: pnpm run check

      - name: Lint check
        run: pnpm lint:check

      - name: Prettier check
        run: pnpm prettier:check
