name: Commitlint
on:
  pull_request:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install
        run: yarn

      - name: Build
        run: yarn build

      - name: Install Commitlint Config
        run: yarn add @vidavidorra/commitlint-config

      - name: Validate commits
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: .github/workflows/commitlint.config.js
        env:
          NODE_PATH: ${{ github.workspace }}/node_modules
